apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linera-respeer-faucet-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

