services:
  faucet:
    image: "${LINERA_IMAGE:-linera}"
    container_name: faucet
    ports:
      - "31080:31080"
    command: [ "./faucet-shard-entrypoint.sh" ]
    volumes:
      - ../output/wallet/faucet:/wallet
      - ../output/wallet/faucet-depositor:/depositor
    environment:
      RUST_LOG: warn
    restart: always
