services:
  faucet:
    image: "${LINERA_IMAGE:-linera}"
    container_name: faucet
    ports:
      - "8080:8080"
    command: [ "./faucet-shard-entrypoint.sh" ]
    volumes:
      - ../output/local/wallet/faucet:/wallet
      - ../output/local/wallet/faucet-depositor:/depositor
