services:
  faucet:
    image: "${LINERA_IMAGE:-linera}"
    container_name: faucet
    ports:
      - "8080:8080"
    command: [ "./faucet-entrypoint.sh" ]
    volumes:
      - ./wallet/faucet:/wallet
