{
 "title": "General",
 "tags": [ "linera" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Proxy requests per second (averaged for the past minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(linera_proxy_request_count[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Error rate (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    (\n        rate(linera_proxy_request_error[1m])\n    ) / (\n        (\n            (\n                rate(linera_proxy_request_success[1m])\n            ) + (\n                rate(linera_proxy_request_error[1m])\n            )\n        )\n    )\n) * 100",
     "legendFormat": "{{method_name}}"
    }
   ]
  },
  {
   "title": "Proxy p99 latency ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(linera_proxy_request_latency_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy p90 latency ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(linera_proxy_request_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy p50 latency ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_proxy_request_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Server requests per second (averaged for the past minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(linera_server_request_count[1m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(linera_server_request_count[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Server Error rate (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    (\n        sum(rate(linera_server_request_error[1m])) by (method_name, pod)\n    ) / (\n        (\n            (\n                sum(rate(linera_server_request_success[1m])) by (method_name, pod)\n            ) + (\n                sum(rate(linera_server_request_error[1m])) by (method_name, pod)\n            )\n        )\n    )\n) * 100",
     "legendFormat": "{{pod}} - {{method_name}}"
    }
   ]
  },
  {
   "title": "Server p99 latency ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_server_request_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server p90 latency ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(linera_server_request_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server p50 latency ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_server_request_latency_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server p99 latency per request type ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_server_request_latency_per_request_type_bucket[1m])) by (le, method_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server p90 latency per request type ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(linera_server_request_latency_per_request_type_bucket[1m])) by (le, method_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server p50 latency per request type ms (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_server_request_latency_per_request_type_bucket[1m])) by (le, method_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Network bytes TX/RX total per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"(proxy|shards)-.*\"}[60s])) by (pod) + sum(rate(container_network_transmit_bytes_total{pod=~\"(proxy|shards)-.*\"}[60s])) by (pod)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"shards-.*\"}[60s])) + sum(rate(container_network_transmit_bytes_total{pod=~\"shards-.*\"}[60s]))",
     "legendFormat": "Total shards"
    }
   ]
  },
  {
   "title": "Container Memory Usage Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=~\"linera.*\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"(proxy|shards).*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=~\"linera.*\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"(proxy|shards)-.*\"}[60s])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"linera-.*\"}[60s])) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[60s]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Container termination",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_last_terminated_reason[1m])) by (pod, reason)",
     "legendFormat": "{{pod}} - {{reason}}"
    }
   ]
  },
  {
   "title": "Container Memory Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod, failure_type) (rate(container_memory_failures_total{pod=~\"(proxy|shards)-.*\", failure_type!=\"pgfault\"}[60s]))",
     "legendFormat": "{{pod}} - {{failure_type}}"
    }
   ]
  },
  {
   "title": "Container termination exit code",
   "type": "timeseries",
   "description": "Some useful codes to remember:\n137 - SIGKILL - can happen on OOMs\n143 - SIGTERM",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_exitcode",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Shards FS read bytes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{container=\"linera-server\"}[60s])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{container=\"linera-server\"}[60s]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Shards FS reads per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_total{container=\"linera-server\"}[60s])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(container_fs_reads_total{container=\"linera-server\"}[60s]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Shards FS written bytes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{container=\"linera-server\"}[60s])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{container=\"linera-server\"}[60s]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Shards FS writes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_total{container=\"linera-server\"}[60s])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(container_fs_writes_total{container=\"linera-server\"}[60s]))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Scylla Cluster Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Scylla Network bytes TX/RX total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"scylla-validator.*\"}[60s])) by (pod) + sum(rate(container_network_transmit_bytes_total{pod=~\"scylla-validator.*\"}[60s])) by (pod)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Scylla Memory Usage Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"scylla-validator.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ScyllaDB Total CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"scylla-validator-.*\"}[60s])) by (pod)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Scylla Memory Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(failure_type) (rate(container_memory_failures_total{container=\"scylla\", failure_type!=\"pgfault\"}[60s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ScyllaDB Container termination",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_last_terminated_reason{pod=~\"(scylla)-.*\"}[1m])) by (pod, reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ScyllaDB FS read bytes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{container=\"scylla\"}[60s])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "ScyllaDB FS reads per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_total{container=\"scylla\"}[60s])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "ScyllaDB FS written bytes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{container=\"scylla\"}[60s])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "ScyllaDB FS writes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_total{container=\"scylla\"}[60s])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "ScyllaDB OOM events per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_oom_events_total{pod=~\"scylla-validator-.*\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}