apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: faucet-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: ebs-storageclass // when multi storageclass exist,you can sepcify
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: depositor-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: ebs-storageclass // when multi storageclass exist,you can sepcify
  resources:
    requests:
      storage: 20Gi
