apiVersion: apps/v1
kind: Deployment
metadata:
  name: faucet-service
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faucet-service
  template:
    metadata:
      labels:
        app: faucet-service
    spec:
      initContainers:
      - name: init-wallet
        image: npool/linera-respeer:latest
        imagePullPolicy: Always
        command:
        - /bin/sh
        - -c
        - |
          if [ ! -f /wallet/wallet.json ]; then
            echo "No wallet found, creating..."
            ./linera --wallet /wallet/wallet.json --keystore /wallet/keystore.json --storage rocksdb:/wallet/client.db wallet init --faucet https://faucet.testnet-conway.linera.net
            ./linera --wallet /wallet/wallet.json --keystore /wallet/keystore.json --storage rocksdb:/wallet/client.db wallet request-chain --faucet https://faucet.testnet-conway.linera.net
          else
            echo "Wallet already exists, skipping init."
          fi
        volumeMounts:
        - name: faucet
          mountPath: /wallet
        - name: depositor
          mountPath: /depositor
      containers:
      - name: faucet-service
        image: npool/linera-respeer:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c", "./faucet-shard-entrypoint.sh"]
        env:
        - name: RUST_LOG
          value: warn
        volumeMounts:
        - name: faucet
          mountPath: /wallet
        - name: depositor
          mountPath: /depositor
      volumes:
      - name: faucet
        persistentVolumeClaim:
          claimName: faucet-pvc
      - name: depositor
        persistentVolumeClaim:
          claimName: depositor-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: faucet-service
  namespace: kube-system
spec:
  ports:
    - name: faucet-service
      port: 31080
      targetPort: 31080
  selector:
    app: faucet-service
