name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - "**"
    paths:
      - 'docker/Dockerfile'
      - 'Cargo.toml'
      - '.github/workflows/docker.yml'
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs on pull-requests
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.run_id }}'
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  # We allow redundant explicit links because `cargo rdme` doesn't know how to resolve implicit intra-crate links.
  RUSTDOCFLAGS: -A rustdoc::redundant_explicit_links -D warnings
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10
  RUST_LOG: warn

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest-16-cores
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build . -f docker/Dockerfile
